export const GET_HOME = "GET_HOME" 
export const GET_HEALTH = "GET_HEALTH" 
export const GET_POLITICS = "GET_POLITICS" 
export const GET_SCIENCE = "GET_SCIENCE" 
export const GET_TECHNOLOGY = "GET_TECHNOLOGY" 
export const GET_WORLD = "GET_WORLD" 
export const GET_DETAIL = "GET_DETAIL"